; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = nologo_esp32c3_super_mini
upload_port = /dev/cu.usbmodem2101
monitor_port = /dev/cu.usbmodem2101
board_build.partitions = min_spiffs.csv
; board_build.f_cpu = 80000000L
build_flags =
    ; -DCORE_DEBUG_LEVEL=4
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=7
    -DCONFIG_BT_NIMBLE_MAX_BONDS=5
    ; Transceiver STBY wired to MCP251863 GPIO0/XSTBY: put the transceiver in standby while sleeping
    ; -DCAN_XSTBY
lib_deps =
    pierremolinaro/ACAN2517FD@^2.1.14
    h2zero/NimBLE-Arduino@^2.3.1
    h2zero/NimBLEOta@^0.2.0
; upload_protocol = custom
; upload_command = env/bin/python ota.py $SOURCE 2D6B001D-BA20-C0A2-BA15-527F856C560C